#! /bin/sh

config(){
    bspc config border_width        2
    bspc config window_gap          5

    bspc config focused_border_color "#A89984"
    bspc config normal_border_color "#282828"
    bspc config border_width 2

    bspc config split_ratio         0.52
    bspc config borderless_monocle  true
    bspc config gapless_monocle     true

    bspc monitor -d I II III IV V VI VII VIII IX S


    xsetroot -cursor_name left_ptr


    feh --bg-fill --no-fehbg ~/.background.jpg
    sxhkd &
    systemctl --user restart polybar
}

config 2>&1 | tee /tmp/bspc.log

