#!/usr/bin/bash

if [ "$#" -eq 3 ]; then
    exec mouse_color $@
fi

COLOR=$(zenity --color-selection --show-palette | sed -e 's/rgb(//' -e 's/)//')

R=$(echo $COLOR | awk -F, '{print $1}')
G=$(echo $COLOR | awk -F, '{print $2}')
B=$(echo $COLOR | awk -F, '{print $3}')

exec mouse_color $R $G $B
