#!/usr/bin/python

import argparse
from collections.abc import Generator
import csv
import json
import sys


def json_printer(gen: Generator):
    print("[")
    try:
        line = gen.__next__()
        print(json.dumps(line), end="")
    except StopIteration:
        pass

    for line in gen:
        print(",\n", json.dumps(line), end="")
    print("\n]")


def jsonl_printer(gen: Generator):
    for line in gen:
        print(json.dumps(line))


def main(f, format):
    match format:
        case "json":
            printer = json_printer
        case "jsonl":
            printer = jsonl_printer
        case _:
            raise Exception("Incorrect format")

    try:
        gen = (dict(r) for r in csv.DictReader(f))
        printer(gen)
    except (BrokenPipeError, KeyboardInterrupt):
        return


if __name__ == "__main__":
    parser = argparse.ArgumentParser()
    parser.add_argument("--format", default="json", choices=["json", "jsonl"])
    parser.add_argument(
        "input", nargs="?", default=sys.stdin, type=argparse.FileType("r")
    )
    args = parser.parse_args()
    main(args.input, args.format)
