#!/bin/bash

set -e


if [ $# -ne 1 ]
  then 
    echo "usage: git initwt <dir>"
    exit 
fi

git init $1
cd $1

# Add base commit to master
git checkout -q $(git commit-tree $(git hash-object -t tree /dev/null) < /dev/null)
git switch -c master 

git checkout -q $(git commit-tree $(git hash-object -t tree /dev/null) < /dev/null)
git switch -c worktree
git config branch.worktree.pushRemote no_push
