#!/bin/bash

set -e


if [ $# -ne 2 ]
  then 
    echo "usage: git clonewt <repo> <dir>"; exit 
fi

git clone $1 $2
cd $2
git checkout $(git commit-tree $(git hash-object -t tree /dev/null) < /dev/null)
git switch -c worktree
git config branch.worktree.pushRemote no_push

