# version: 1.0.0

add_newline = true
continuation_prompt = "[▸▹ ](dimmed white)"

format = """($directory$git_branch${custom.git_status_dirty}$git_status$nix_shell$fill$git_metrics\n)\
$time\
$cmd_duration\
$jobs\
$character"""

right_format = """
$git_commit\
$git_state\
$direnv\
$nodejs\
$python\
$rust\
$zig\
"""

[fill]
symbol = ' '

[character]
format = " $symbol "
success_symbol = "[󰅂](bold bright-yellow)"
error_symbol = "[󰅂](purple)"

[directory]
format = '[$path]($style)[$read_only]($read_only_style)'
repo_root_format = '[$before_root_path]($before_repo_root_style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)'
truncation_length = 2
truncate_to_repo = false
truncation_symbol = '…/'
read_only = '[ro]'
style = "blue"
before_repo_root_style = "dimmed blue"
repo_root_style = "bold blue"


[cmd_duration]
format = "[ $duration](white)"

[jobs]
format = "[ $symbol$number]($style)"
style = "dimmed red"
symbol = "✦ "

[time]
disabled = false
format = "[$time]($style)"
time_format = "%R"
utc_time_offset = "local"
style = "dimmed white"

[git_branch]
format = "[ $branch(:$remote_branch)]($style)"
symbol = "[△](bold bright-blue)"
style = "bright-blue"
truncation_symbol = "⋯"
truncation_length = 11
only_attached = true

[git_metrics]
format = '([▴$added]($added_style)) ([▿$deleted]($deleted_style))'
added_style = 'dimmed green'
deleted_style = 'dimmed red'
ignore_submodules = true
disabled = false

[git_status]
format = " $ahead_behind[ $stashed]($style)"
style = "bold dimmed purple"
ahead = "[⇡](green)"
behind = "[⇣](red)"
stashed = "≡"

[custom.git_status_dirty]
when = 'test -n "$(git status --porcelain 2>/dev/null)"'
symbol = " •"
style = "red dimmed"
format = "[$symbol]($style)"
shell = ["sh"]

[nodejs]
format = "[ ${symbol}($version)](bold bright-green)"
version_format = "${raw}"
symbol = " "
detect_files = ["package-lock.json", "yarn.lock"]
detect_folders = ["node_modules"]
detect_extensions = []

[python]
format = "[ ${symbol}${version}]($style)"
symbol = " "
version_format = "${raw}"
style = "bold bright-yellow"

[rust]
format = "[ $symbol$version]($style)"
symbol = " "
version_format = "${raw}"
style = "bold red"
