#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true
polybar &
xrandr --output DP-2 --mode 2560x1440 --rate 144

xsetroot -cursor_name left_ptr &
setxkbmap -layout us -variant qwerty-fr -option compose:rwin &

bspc rule -a tev state=floating
bspc rule -a polkit-gnome-authentication-agent-1 state=floating

~/.wall/wall
polybar &
picom &
dunst &
