#! /bin/sh
~/.screenlayout/layout.sh

pgrep -x sxhkd >/dev/null || SXHKD_SHELL=/bin/bash sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width 2
bspc config window_gap 5

bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

xsetroot -cursor_name left_ptr &
setxkbmap -layout us -variant qwerty-fr -option compose:rwin &

bspc rule -a tev state=floating
bspc rule -a polkit-gnome-authentication-agent-1 state=floating
bspc rule -a matplotlib state=floating
bspc rule -a Matplotlib state=floating


~/.wall/wall
if type "xrandr"; then
  for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
    MONITOR=$m polybar --reload &
  done
else
  polybar --reload &
fi

picom &
dunst &
xss-lock slock&

xset s 0 0 
xset dpms 0 0 0 

eval $(ssh-agent)
ssh-add ~/.ssh/id_ed25519

dbus-update-activation-environment --all &
gnome-keyring-daemon --start --components=secrets &
